---
  - name: Instances setup - Zookeeper instances creation instances_setup_zookeeper {{ instances_setup_zookeeper }}
    hosts: localhost
    connection: local
    vars:
      instances_setup_zookeeper: false
      aws_ec2_instances_setup_zookeeper: false
      # ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
      instance_tags_env: zookeeper
    gather_facts: false
    tags: [ 'never', 'instances_setup_zookeeper' ]
    tasks:
      - name: Zookeeper instance create AWS EC2
        include_tasks: ../environments/aws/01-instances-setup/01-ec2-zookeeper-chorum.yaml
        when: instances_setup_zookeeper and aws_ec2_instances_setup_zookeeper
        with_items: "{{ groups['zookeeper'] }}"
        loop_control:
          loop_var: zookeeper_host


      
