# In AWS IAM, created a User Group by name MyMyRnDWorkGroup and in it created 
# a Group Policy by name AWS-CLI-Additional-Policies with below JSON

# Also created an user by name ansible-kafka-cluster-user and attached this user to the above mentioned AWS IAM Group
# .pem file for this user is stored at a location specified in "ansible_ssh_private_key_file" variable of hosts.yaml for inventoris/dev/hosts.yaml

# https://serverfault.com/questions/545546/how-to-specify-an-iam-role-for-an-amazon-ec2-instance-being-launched-via-the-aws/548083#548083
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:ListInstanceProfiles",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*"
        }
    ]
}