---
  all:
    vars:
      # ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
      host_image_id: ami-0739f8cdb239fe9ae
      host_region_id: us-east-1
      host_keypair_name: ansible-kafka-cluster-setup-keypair
      host_sec_group_id: sg-0b37177cd70a71b61
      host_ssh_user: "ubuntu"
      instance_tags_purpose: cloudera-mastery
      instance_tags_env: undefined_instance_tags_env
      instances_setup_zookeeper: false
      host_subnent_id: subnet-0b4610882f095622b
      zookeeper_user: zookeeper
      zookeeper_group: zookeeper
      instance_tags_env_zookeeper: zookeeper
      instance_tags_env_kafka: kafka
      kafka_broker_user: kafkaborker
      kafka_broker_group: kafkabroker
      kafka_broker:
        data_dir:
          - /var/lib/kafka/data

  localhosts:
    vars:
      ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
    hosts:
      localhost:

  local:
    vars:
      ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

  dynamic_hosts:
    
  zookeeper:
    vars:
      instance_tags_env: zookeeper
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_become: true
      ansible_port: 22
      ansible_ssh_private_key_file: ~/ansible-kafka-cluster-setup-keypair.pem
      user: "{{ host_ssh_user }}"
      become: true
      become_method: sudo
      become_user: "{{ host_ssh_user }}"
    hosts:
      ec2-zookeeper1:
        zookeeper_id: 1
        host_subnent_id: subnet-0b4610882f095622b
        # inventory_hostname: ec2-a-b-c-d.compute-1.amazonaws.com
        # ansible_host: a.b.c.d

  kafka_broker:
    vars:
      instance_tags_env: kafka
    hosts:
      ec2-kafka-broker1:
        broker_id: 1
        kafka_broker_custom_properties:
          brocker.rack: us-east-1a
          host_subnent_id: subnet-0b4610882f095622b
          replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      ec2-kafka-broker2:
        broker_id: 2
        kafka_broker_custom_properties:
          broker.rack: us-east-1b
          host_subnent_id: subnet-013372298bebb6401
          replica.selector.class: org.apache.kafka.common.replica.RacsAwareReplicaSelector
      ec2-kafka-broker3:
        broker_id: 3
        kafka_broker_custom_properties:
          broker.rack: us-east-1c
          host_subnent_id: subnet-0b48a4f6e35d94048
          replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector

  kafka_connect:
    vars:
      kafka_connect_user: kafkaconnect
      kafka_connect_group: kafkaconnect
    hosts:
      ec2-kafka-connect:

  kafka_cluster_control_host:
      hosts:
        localhost
