all:
  vars:
    env_type: aws
    env_aws_enabled: true
    aws_access_key_id: {{ lookup('env', 'AWS_ACCESS_KEY_ID') }}
    aws_secret_access_key: {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}
zookeeper_quorum:
  vars:
  hosts:
    ec2-zookeeper-1:
      vars:
        ansible_host: ec2-zookeeper-1

kafka_brokers:
  vars:
  hosts:
    ec2-kafka-1:
      vars:
        ansible_host: ec2-kafka-1

cluster_nodes:
  vars:
  hosts:
    children:
      zookeeper_quorum:
      kafka_brokers: