# https://www.middlewareinventory.com/blog/run-ansible-playbook-locally/#Method1_Specify_Localhost_in_your_hosts_directive_of_your_playbook
- name: AWS EC2 Launching AWS instance using Ansible for Zookeeper host {{ zookeeper_host }}
  vars:
    aws_ec2_instances_setup_zookeeper: false
  tags: [ 'never', 'aws_ec2_instances_setup_zookeeper' ]
  when: aws_ec2_instances_setup_zookeeper
  ec2:
    # state: present
    assign_public_ip: yes
    instance_type: t2.micro
    image: "{{ hostvars[zookeeper_host].host_image_id }}"
    region: "{{ hostvars[zookeeper_host].host_region_id }}"
    key_name: "{{ hostvars[zookeeper_host].host_keypair_name }}"
    wait: yes
    # group: Ansible
    # count: 1
    # https://github.com/ansible/ansible-modules-core/issues/1009
    instance_tags:
      purpose: "{{ instance_tags_purpose }}"
      Env: "{{ instance_tags_env }}"
      Name: "{{ instance_tags_env }}-{{ hostvars[zookeeper_host].zookeeper_id }}"
    exact_count: 1
    count_tag:
      purpose: "{{ instance_tags_purpose }}"
      Env: "{{ instance_tags_env }}"
      Name: "{{ instance_tags_env }}-{{ hostvars[zookeeper_host].zookeeper_id }}"
    vpc_subnet_id: "{{ hostvars[zookeeper_host].host_subnent_id }}"
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    # delegate_to: 127.0.0.1

      
