# https://www.middlewareinventory.com/blog/run-ansible-playbook-locally/#Method1_Specify_Localhost_in_your_hosts_directive_of_your_playbook
- name: AWS EC2 Launching AWS instance using Ansible for Kafka host {{ kafka_host }}
  vars:
    aws_ec2_instances_setup_kafka: false
  tags: [ 'never', 'aws_ec2_instances_setup_kafka' ]
  when: aws_ec2_instances_setup_kafka
  ec2:
    # state: present
    wait: yes
    assign_public_ip: yes
    instance_type: t2.micro
    image: "{{ hostvars[kafka_host].host_image_id }}"
    region: "{{ hostvars[kafka_host].host_region_id }}"
    key_name: "{{ hostvars[kafka_host].host_keypair_name }}"
    group_id: "{{ hostvars[zookeeper_host].host_sec_group_id }}"
    # group: Ansible
    # count: 1
    # https://github.com/ansible/ansible-modules-core/issues/1009
    instance_tags:
      purpose: "{{ instance_tags_purpose }}"
      Env: "{{ instance_tags_env }}"
      Name: "{{ instance_tags_env }}-{{ hostvars[kafka_host].broker_id }}"
    exact_count: 1
    count_tag:
      purpose: "{{ instance_tags_purpose }}"
      Env: "{{ instance_tags_env }}"
      Name: "{{ instance_tags_env }}-{{ hostvars[kafka_host].broker_id }}"
    vpc_subnet_id: "{{ hostvars[kafka_host].host_subnent_id }}"
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    # delegate_to: 127.0.0.1
  register: ec2

  # https://github.com/chrismeyersfsu/playbook-ec2_properties/blob/master/new_group.yml

  - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

  - name: Wait a little longer for centos
      pause: seconds=20

  - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        groups: dynamic_hosts
        ansible_ssh_host: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        # ansible_ssh_private_key_file: '{{ ansible_ssh_private_key_file }}'
        ansible_ssh_user: "{{ hostvars[kafka_host].host_ssh_user }}"
        ec2_vars: "{{ ec2.results[item.0]['instances'][0] }}"
        ec2_instance_ids: "{{ ec2.results[item.0]['instance_ids'] }}"
      # with_indexed_items: ec2_instances
      with_items: ec2.results
  

      
