---
  - name: Software Install Zookeeper
    hosts: zookeeper
    gather_facts: false
    vars:
      instances_software_install_zookeeper: false
      aws_ec2_instances_software_intall_zookeeper: false
    tags: [ 'never', 'instances_software_install_zookeeper' ]
    tasks:
      - name: Zookeeper Install on AWS EC2
        include: ../environments/aws/02-software-install/01-zookeeper-install.yaml
        vars:
          zookeeper_host: {{ inventory_hostname }}
        when: instances_software_install_zookeeper and aws_ec2_instances_software_intall_zookeeper